"""Add interview_type field to interviews table

Revision ID: f807ebee538d
Revises: 6228e3dbd260
Create Date: 2025-11-16 00:08:37.470647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f807ebee538d'
down_revision: Union[str, None] = '6228e3dbd260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.drop_column('answers', 'audio_url')
    op.drop_column('answers', 'audio_duration_seconds')
    op.add_column('interviews', sa.Column('interview_type', sa.Enum('STANDARD', 'RESUME_GRILL', 'COMPANY_PREP', name='interviewtype'), nullable=False))
    op.alter_column('interviews', 'job_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_interviews_interview_type'), 'interviews', ['interview_type'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_questions_interview_id'), 'questions', ['interview_id'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_questions_interview_id'), table_name='questions')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_interview_type'), table_name='interviews')
    op.alter_column('interviews', 'job_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('interviews', 'interview_type')
    op.add_column('answers', sa.Column('audio_duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    # ### end Alembic commands ###
